// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwASH0FFYmeMQuxpwu5ONijvtzO3u-MXQ',
    appId: '1:468323447663:web:66b38b1c4eb25a5767ae9a',
    messagingSenderId: '468323447663',
    projectId: 'notifications-64c7b',
    authDomain: 'notifications-64c7b.firebaseapp.com',
    storageBucket: 'notifications-64c7b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYubI8laHnnF7PtltDLzpqlk0dbl0pIFw',
    appId: '1:468323447663:android:33c15e24d273bc2567ae9a',
    messagingSenderId: '468323447663',
    projectId: 'notifications-64c7b',
    storageBucket: 'notifications-64c7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUqFpdRqkG7M5NvicXeUmJZwQggXPqHzY',
    appId: '1:468323447663:ios:db75573672c0536b67ae9a',
    messagingSenderId: '468323447663',
    projectId: 'notifications-64c7b',
    storageBucket: 'notifications-64c7b.appspot.com',
    iosBundleId: 'com.example.notifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUqFpdRqkG7M5NvicXeUmJZwQggXPqHzY',
    appId: '1:468323447663:ios:f2d559d94a976e4067ae9a',
    messagingSenderId: '468323447663',
    projectId: 'notifications-64c7b',
    storageBucket: 'notifications-64c7b.appspot.com',
    iosBundleId: 'com.example.notifications.RunnerTests',
  );
}
